In [32]:
import numpy as np

In [60]:
n = [2, 3, 3, 1]
print(f"layer 1: {n[0]}")
print(f"layer 2: {n[1]}")
print(f"layer 3: {n[2]}")
print(f"layer 4: {n[3]}")

layer 1: 2
layer 2: 3
layer 3: 3
layer 4: 1


In [73]:
W1 = np.random.randn(n[1], n[0])
W2 = np.random.randn(n[2], n[1])
W3 = np.random.randn(n[3], n[2])
b1 = np.random.randn(1, n[1])
b2 = np.random.randn(1, n[2])
b3 = np.random.randn(1, n[3])
# Standard shape = (1, n_units)
print("Weights for layer 1 shape:", W1.shape)
print("Weights for layer 2 shape:", W2.shape)
print("Weights for layer 3 shape:", W3.shape)
print("bias for layer 1 shape:", b1.shape)
print("bias for layer 2 shape:", b2.shape)
print("bias for layer 3 shape:", b3.shape)

Weights for layer 1 shape: (3, 2)
Weights for layer 2 shape: (3, 3)
Weights for layer 3 shape: (1, 3)
bias for layer 1 shape: (1, 3)
bias for layer 2 shape: (1, 3)
bias for layer 3 shape: (1, 1)


In [62]:
X = np.array([
    [150, 70], # it's our boy Jimmy again! 150 pounds, 70 inches tall. 
    [254, 73],
    [312, 68],
    [120, 60],
    [154, 61],
    [212, 65],
    [216, 67],
    [145, 67],
    [184, 64],
    [130, 69]
])

print(X.shape) # prints (10, 2)

(10, 2)


In [63]:
y = np.array([
    0,  # whew, thank God Jimmy isn't at risk for cardiovascular disease.
    1,   # yikes, this guy wasn't as lucky
    1, # ok, this guy should have seen it coming. 5"8, 312 lbs isn't great.
    0,
    0,
    1,
    1,
    0,
    1,
    0
])
m = 10

# we need to reshape to a n^[3] x m matrix
Y = y.reshape(n[3], m)
Y.shape

(1, 10)

In [37]:
def sigmoid(arr):
    return 1 / (1 + np.exp(-1 * arr))

In [99]:
# number of samples
m = 10

A0 = X
# layer 1
Z1 = A0 @ W1.T + b1
# (n_samples, n_nodes in layer 1)
assert Z1.shape == (m, n[1])
A1 = sigmoid(Z1)
print(Z1)
print(A1)

# layer 2
Z2 = A1 @ W2.T + b2
assert Z2.shape == (m, n[2])
A2 = sigmoid(Z2)

# layer 3
Z3 = A2 @ W3.T + b3
assert Z3.shape == (m, n[3])
A3 = sigmoid(Z3)

y_hat = A3
y_hat


[[ 109.19992271  -85.12368168  -93.13681541]
 [ 217.17169954 -139.41911304 -175.77704793]
 [ 282.12490549 -168.99071115 -224.54142319]
 [  84.54019444  -68.49162593  -72.96215657]
 [ 119.82500525  -86.24409733  -99.97144225]
 [ 178.38781744 -116.77131409 -145.12594162]
 [ 181.20241871 -119.05970808 -147.54849791]
 [ 106.036693    -82.21009925  -90.3091687 ]
 [ 149.45503979 -102.13289413 -122.95378235]
 [  88.7365226   -74.63733032  -77.41415803]]
[[1.00000000e+00 1.07461963e-37 3.55791038e-41]
 [1.00000000e+00 2.82519570e-61 4.58139819e-77]
 [1.00000000e+00 4.05757594e-74 3.04017757e-98]
 [1.00000000e+00 1.79665547e-30 2.05559718e-32]
 [1.00000000e+00 3.50480962e-38 3.82784446e-44]
 [1.00000000e+00 1.93580964e-51 9.38867649e-64]
 [1.00000000e+00 1.96347674e-52 8.32724884e-65]
 [1.00000000e+00 1.97973718e-36 6.01487169e-40]
 [1.00000000e+00 4.40806163e-45 3.99807371e-54]
 [1.00000000e+00 3.84963271e-33 2.39584296e-34]]


array([[0.83868501],
       [0.83868501],
       [0.83868501],
       [0.83868501],
       [0.83868501],
       [0.83868501],
       [0.83868501],
       [0.83868501],
       [0.83868501],
       [0.83868501]])